dubbo:
  application:
    name: view-facade
  registry:
    address: zookeeper://192.168.140.129:2181
  protocol:
    port: 20883
server:
  port: 9094
spring:
  redis:
    host: 192.168.140.134
    port: 6379
    password: qfjava
    jedis:
      pool:
        max-active: 8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_my_device?serverTimezone=Asia/Shanghai
    username: root
    password: 7901
    type: com.alibaba.druid.pool.DruidDataSource

# 指明mapper映射文件的位置
mybatis:
  mapper-locations: classpath:META-INF/mapper/*.xml
